// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyszjhdpydfzzaeoqelo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5c3pqaGRweWRmenphZW9xZWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTY0NjcsImV4cCI6MjA2ODMzMjQ2N30.zVjlwjkdj6r6LtCvVq1yZ522xEXF_Iix88l_eW8ohrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});